"use client";

import type { Metadata } from "next";
import { geistSans, geistMono, fraunces, manrope, chivo, fira, hanken } from "./font";
import "./globals.css";
import { AuthContextProvider } from "./context/auth-context";
import { Toaster } from "sonner";
import { TeacherFormContextProvider } from "./context/teaching-form-context";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fraunces.variable} ${manrope.variable} ${chivo.variable} ${fira.variable} ${hanken.variable} antialiased`}
      >
        <AuthContextProvider>
          <TeacherFormContextProvider>
            <Toaster position="top-center"/>
            <main>{children}</main>
          </TeacherFormContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
